# Generated by Django 4.0.2 on 2022-03-03 17:00

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sport_site', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='active_set',
            field=models.IntegerField(default=1, verbose_name='Текущая партия'),
        ),
        migrations.AddField(
            model_name='match',
            name='blue_points_set_1',
            field=models.IntegerField(default=0, verbose_name='Очки синих в 1 партии'),
        ),
        migrations.AddField(
            model_name='match',
            name='blue_points_set_2',
            field=models.IntegerField(default=0, verbose_name='Очки синих во 2 партии'),
        ),
        migrations.AddField(
            model_name='match',
            name='blue_points_set_3',
            field=models.IntegerField(default=0, verbose_name='Очки синих в 3 партии'),
        ),
        migrations.AddField(
            model_name='match',
            name='blue_set_score',
            field=models.IntegerField(default=0, verbose_name='Выигранные партии синей команды'),
        ),
        migrations.AddField(
            model_name='match',
            name='blue_squad',
            field=models.CharField(default='Синяя команда', max_length=128, verbose_name='Состав синей команды'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='match',
            name='red_points_set_1',
            field=models.IntegerField(default=0, verbose_name='Очки красных в 1 партии'),
        ),
        migrations.AddField(
            model_name='match',
            name='red_points_set_2',
            field=models.IntegerField(default=0, verbose_name='Очки красных во 2 партии'),
        ),
        migrations.AddField(
            model_name='match',
            name='red_points_set_3',
            field=models.IntegerField(default=0, verbose_name='Очки красных в 3 партии'),
        ),
        migrations.AddField(
            model_name='match',
            name='red_set_score',
            field=models.IntegerField(default=0, verbose_name='Выигранные партии красной команды'),
        ),
        migrations.AddField(
            model_name='match',
            name='red_squad',
            field=models.CharField(default='Красная команда', max_length=128, verbose_name='Состав красной команды'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='match',
            name='date',
            field=models.DateField(default=datetime.date.today, verbose_name='Дата матча'),
        ),
        migrations.AlterField(
            model_name='match',
            name='sport',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sport_site.sports', verbose_name='Вид спорта'),
        ),
    ]
