# Generated by Django 4.0.2 on 2022-03-03 18:17

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sport_site', '0002_match_active_set_match_blue_points_set_1_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='EndedMatches',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=datetime.date.today, verbose_name='Дата матча')),
                ('red_squad', models.CharField(max_length=128, verbose_name='Состав красной команды')),
                ('blue_squad', models.CharField(max_length=128, verbose_name='Состав синей команды')),
                ('red_set_score', models.IntegerField(default=0, verbose_name='Выигранные партии красной команды')),
                ('blue_set_score', models.IntegerField(default=0, verbose_name='Выигранные партии синей команды')),
                ('red_points_set_1', models.IntegerField(default=0, verbose_name='Очки красных в 1 партии')),
                ('red_points_set_2', models.IntegerField(default=0, verbose_name='Очки красных во 2 партии')),
                ('red_points_set_3', models.IntegerField(default=0, verbose_name='Очки красных в 3 партии')),
                ('blue_points_set_1', models.IntegerField(default=0, verbose_name='Очки синих в 1 партии')),
                ('blue_points_set_2', models.IntegerField(default=0, verbose_name='Очки синих во 2 партии')),
                ('blue_points_set_3', models.IntegerField(default=0, verbose_name='Очки синих в 3 партии')),
                ('active_set', models.IntegerField(default=1, verbose_name='Текущая партия')),
                ('sport', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sport_site.sports', verbose_name='Вид спорта')),
            ],
            options={
                'verbose_name': 'Сыгранный матч',
                'verbose_name_plural': 'Сыгранные матчи',
            },
        ),
    ]
